name: template
description: Default template.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  dio: ^5.0.3
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  go_router: ^10.0.0
  cached_network_image: ^3.2.3
  flutter_spinkit: ^5.2.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  carousel_slider: ^4.2.1
  gradient_like_css: ^1.0.1
  flutter_rating_stars: ^1.0.3+4
  shimmer: ^3.0.0
  page_transition: ^2.0.9
  modal_bottom_sheet: ^3.0.0-pre
  dismissible_page: ^1.0.2
  photo_view: ^0.14.0
  masonry_grid: ^1.0.0
  change_app_package_name: ^1.1.0
  scrollable_positioned_list: ^0.3.8
  google_maps_flutter_android: ^2.4.16
  flutter_slidable: ^3.0.0
  grouped_list: ^5.1.2
  flutter_animate: ^4.2.0+1
  sliver_tools: ^0.2.12
  lottie: ^2.6.0
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  camera: ^0.10.5+4
  smooth_page_indicator: ^1.1.0
  pinput: ^3.0.1
  extended_masked_text: ^2.3.1
  animations: ^2.0.8
  geolocator: ^10.0.1  
  permission_handler: ^11.0.0
  flutter_map: ^5.0.0
  flutter_map_marker_cluster: ^1.2.0
  flutter_map_animations: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  lint: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/lottie/